### ISSUE TITLE
Marketplace doesn't seem to subtract the test LMR from my balance every time I buy a contract.

### ISSUE THREAD

**Issue by jschultz2423** [Lumerin-protocol/proxy-router#11]
Only seems to subtract my rETH

**Comment by joshtitan** [comment]
I've looked at the following contract, and here's my findings: https://ropsten.etherscan.io/address/0xE1987d56f680d0daF6Cb17b5D034488F60834DF9

The contract purchase price was entered as 13, so after applying the erc20 decimals function to the display, the purchase price will show as 0.00000013 LMR. The value of 0.00000013 LMR being sent to this contract is an expected phenomenon

My assumption is that in the initial creation of the smart contract, the value being provided by the seller is not being multiplied by 10^8

**Comment by jschultz2423** [comment]
Addressed
