### ISSUE TITLE
Hashrate dropped 200TH/s to 10TH/s

### ISSUE THREAD

**Issue by altitan** [Lumerin-protocol/proxy-router#2]
200TH/s contract connected to slushpool dropped to 10TH/s with one worker offline (9.7 TH/s) and the other at 316.8 GH/s (disabled)- contract address 0x8F3E1DC81D095f4DC55F9072a8011095ABAdfb5D

**Comment by jschultz2423** [comment]
Potentially issue from Marshall turning off miners or from overloading router
