### ISSUE TITLE
LMR token doesn't update after purchasing contract

### ISSUE THREAD

**Issue by jyi428** [Lumerin-protocol/proxy-router#33]
Steps to reproduce:

1. Select a contract and click "buy"
2. Go through the buying process
3. After the purchase is a success
4. The LMR token balance doesn't change and doesn't reflect the actual balance.

**Comment by joshtitan** [comment]
we need to make it so that the value of LMR next to the "Import LMR From Metamask" updates mid session instead of just on a page refresh.
Confirmed on chain that tokens are being moved as expected. LMR balance is updated on a page refresh

**Comment by jschultz2423** [comment]
Ticketed created for this additional functionality. Will address when resourcing permits
