### ISSUE TITLE
Purchased 12 hr  100 TH contract that peaked at 3.75 TH then crashed to 0 within 2 hours of showing up in Workers

### ISSUE THREAD

**Issue by Zocalolocal** [Lumerin-protocol/proxy-router#8]
Contract eventually showed in Worker, but for only 2 hours.  The first hour, my 100 TH contact peaked at 3.75 TH and then crashed to 0 in the second hour.

**Comment by jschultz2423** [comment]
Should be fixed by latest changes. Will attempt to recreate when testing re-opens
