### ISSUE TITLE
Worker not show up on Luxor Pool 

### ISSUE THREAD

**Issue by Zocalolocal** [Lumerin-protocol/proxy-router#9]
Purchased a 24 hour 100 TH hashing contract at 11:50 AM PST for Luxor Pool and as of 3:30 PM PST it hasn't shown up as a worker in the dashboard.  However the Marketplace site says it is 15% into the hashing contract

**Comment by jschultz2423** [comment]
Should be fixed as a result of Ryans latest updates. Will test when marketplace testing reopens
